### PR TITLE
allow loading schemas from files with any extension

### LINKED ISSUE #11: "error:  Unexpected token :" on Windows 10 / node v5.6.0
Sadly, it gives me no more than this:
```
$ ajv validate -s minimal.jsonschema -d minimal.json
error:  Unexpected token :
```

This is running via bash in Windows 10 on node v5.6.0 and the latest ajv-cli.

### PR DESCRIPTION
**Pull request by andreineculau**
should fix #11 and #13

### CODE REVIEW

**Comment by epoberezkin** [comment]
I think it's a bit rough approach?... I'd only require .js files and parse everything else and report errors if it doesn't parse rather than throw exception.
If JSON file has syntax error it would simply throw.

**Comment by andreineculau** [comment]
not only that would be a breaking change since today I can pass on "path/to/schema" as an argument and the require call would find "path/to/schema.js" and load that instead (similarly, since you give the option of loading node modules, I would prefer to write schemas in coffeescript, and just run ajv-cli via `node -r coffee-script/register path/to/bin/ajv-cli.js`), but that's also a different improvement altogether

**Comment by epoberezkin** [comment]
Yes, it makes sense. I guess what I really didn't like is that it would have to parse JSON file twice to understand there is an issue with it... Also try inside try looks a bit weird.

I think the breaking change could be to explicitly specify via some option that require has to be used rather than JSON.parse. E.g. use -S (or -D) for require and -s/-d for JSON parse

**Comment by epoberezkin** [comment]
in 0.9.0

**Pull request merged**
