### PR TITLE
Rename README.mdown to README.md

### PR DESCRIPTION
**Pull request by ehmicky**
So that GitHub properly renders the markdown file.

### CODE REVIEW

**Comment by epoberezkin** [comment]
@ehmicky sorry, I am not sure if I see the difference here and in your repo branch. Can you tell me what it is?

**Comment by ehmicky** [comment]
I renamed `README.mdown` to `README.md`

Yesterday, when I looked at the README file, it was not being rendered as HTML by GitHub. I thought this was due to file extension being `mdown` instead of `md`, so proposed this change.

Looking at it today, the README file is correctly rendered by GitHub, so it must have been a local problem, or a temporary GitHub problem. So this looks a bit stupid now, I am closing this.

**Comment by epoberezkin** [comment]
I don't mind the change, I will merge it. .md is definitely a more conventional extension. I was just trying to understand the visual difference :)

**Comment by epoberezkin** [comment]
Can you re-open as I can't...

**Comment by ehmicky** [comment]
Done in #26

**Pull request closed without merging**
