### PR TITLE
Update ajv and other dependencies

### PR DESCRIPTION
**Pull request by cyplo**
This updates `ajv` to the newest published one - would it be okay for you to publish version of `ajv-cli` with these changes as well ?

### CODE REVIEW

**Comment by cyplo** [comment]
It made it not compatible with node4 but all other CI jobs succeeded  - let me know if you'd like me to fix that.

**Comment by epoberezkin** [comment]
We can drop  node 4 from travis tests. Also, no need to update minor versions (they are picked up with ^ semver) - only major versions need changing.

**Comment by cyplo** [comment]
Thanks ! Let me know if it looks better now @epoberezkin :)

**Comment by blontic** [comment]
Hi all, just wondering if there is any update on this? We are missing some functionality until it's updated. thanks

**Pull request merged**
